wkdais_project/client_info/urls.py
from django.conf.urls import url

from .views import(
    client_list, ClientCreate, client_detail,
    ClientDelete, ClientUpdate, activity_list,
    activity_detail, ActivityCreate, ActivityUpdate,
    ActivityDelete, client_payments, payment_detail,
    PaymentCreate, PaymentDelete)

urlpatterns = [
    url(r'^clientlist/$',
        client_list,
        name='client_list'),
    url(r'^client/create/$',
        ClientCreate.as_view(),
        name='client_create'),
    url(r'^client/(?P<slug>[\w\-]+)/$',
        client_detail,
        name='client_detail'),
    url(r'^client/delete/(?P<slug>[\w\-]+)/$',
        ClientDelete.as_view(),
        name='client_delete'),
    url(r'^client/update/(?P<slug>[\w\-]+)/$',
        ClientUpdate.as_view(),
        name='client_update'),
    url(r'^client/payments/(?P<slug>[\w\-]+)/$',
        client_payments,
        name='client_payments'),
    url(r'^payment/create/$',
        PaymentCreate.as_view(),
        name='payment_create'),
    url(r'^payment/(?P<id>[\w\-]+)/$',
        payment_detail,
        name='payment_detail'),
    url(r'^payment/delete/(?P<id>[\w\-]+)/$',
        PaymentDelete.as_view(),
        name='payment_delete'),
    url(r'^activitylist/$',
        activity_list,
        name='activity_list'),
    url(r'^activity/create/$',
        ActivityCreate.as_view(),
        name='activity_create'),
    url(r'^activity/(?P<slug>[\w\-]+)/$',
        activity_detail,
        name='activity_detail'),
    url(r'^activity/update/(?P<slug>[\w\-]+)/$',
        ActivityUpdate.as_view(),
        name='activity_update'),
    url(r'^activity/delete/(?P<slug>[\w\-]+)/$',
        ActivityDelete.as_view(),
        name='activity_delete'),
]

wkdais_project/wkdais_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from client_info import urls as client_urls
from receipt_app import urls as receipt_urls

from .views import redirect_root

urlpatterns = [
    url(r'^$', redirect_root),
    url(r'^receipt/', include(receipt_urls)), # used for printing recipts
    url(r'^', include(client_urls)),
    #url(r'^client/', include(client_urls)),
    url(r'^admin/', admin.site.urls),
]

wkdais_project/client_info/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.forms import ModelForm
from django.core.urlresolvers import reverse

# Create your models here.


class Client(models.Model):

    first_name = models.CharField(
        max_length=50)
    last_name = models.CharField(
        max_length=50)
    middle_name = models.CharField(
        max_length=50)
    birth_date = models.DateField(
        null=True)
    conviction_date = models.DateField(
        blank=True,
        null=True)
    case_number = models.CharField(
        max_length = 20,
        blank=True,
        null=True)
    assessed_date = models.DateField(
        blank=True,
        null=True)
    intake_date = models.DateField(
        blank=True,
        null=True)
    balance_cf = models.DecimalField(
        null=True,
        max_digits=7,
        decimal_places=2,
        default='0.00')
    complete = models.NullBooleanField(
        default=True)
    completed_date = models.DateField(
        blank=True,
        null=True)
    paid_in_full = models.NullBooleanField(
        default=False)
    total_paid = models.DecimalField(
        default ='0.00',
        max_digits = 7,
        decimal_places=2)
    total_billed = models.DecimalField(
        default ='0.00',
        max_digits = 7,
        decimal_places=2)
    paid_in_full_date = models.DateField(
        blank=True,
        null=True)
    non_compliant = models.NullBooleanField(
        blank=True,
        null=True)
    non_compliant_date = models.DateField(
        blank=True,
        null=True)
    inactive = models.NullBooleanField(
        blank=True,
        null=True)
    inactive_date = models.DateField(
        blank=True,
        null=True)
    street_address = models.CharField(
        max_length=200,
        blank=True,
        null=True)
    city = models.CharField(
        max_length=75,
        blank=True,
        null=True)
    state = models.CharField(
        max_length=4,
        blank=True,
        null=True)
    zip_code = models.CharField(
        max_length=15,
        blank=True,
        null=True)
    bad_address = models.BooleanField(
        default = False)
    phone_number = models.CharField(
        max_length=15,
        blank=True,
        null=True)
    work_phone_number = models.CharField(
        max_length=15,
        blank=True,
        null=True)
    ssn = models.CharField(
        max_length=15,
        blank=True,
        null=True)
    court = models.CharField(
        max_length=15,
        blank=True,
        null=True)
    office_number = models.CharField(
        max_length=255,
        blank=True,
        null=True)
    dui = models.CharField(
        max_length=5,
        default = '1st')
    comments = models.TextField(
        blank=True,
        null=True,
        help_text='Best Pratice -> DATE: (comment)')
    reactivate_date = models.DateField(
        blank=True,
        null=True)
    program = models.IntegerField(
        blank=True,
        null=True)
    byn = models.CharField(
        max_length=1,
        blank=True,
        null=True)
    slug = models.SlugField(
        max_length=31,
        unique=True,
        help_text='A label for a url config')

    class Meta:
        ordering = ['last_name']
        unique_together = ("first_name",
                           "middle_name",
                           "last_name",
                           "birth_date")
    def __str__(self):
        return self.first_name +' '+ self.last_name

    def get_absolute_url(self):
        return reverse('client_detail',
                       kwargs={'slug': self.slug})

    def get_delete_url(self):
        return reverse('client_delete',
                       kwargs={'slug': self.slug})

    def get_update_url(self):
        return reverse('client_update',
                       kwargs={'slug': self.slug})

    def get_payments_url(self):
        return reverse('client_payments',
                       kwargs={'slug': self.slug})

    def get_receipt_url(self):
        return reverse('client_receipt',
                       kwargs={'slug': self.slug})

    def update_total_paid(self, payment):
        self.total_paid += payment
        self.update_paid_in_full()

    def update_total_billed(self, cost):
        self.total_billed += cost
        self.update_paid_in_full()

    def update_paid_in_full(self):
        if self.total_paid >= self.total_billed:
            self.paid_in_full = True
        else:
            self.paid_in_full = False

class ClientActivities(models.Model):
    activity_ID = models.BigIntegerField(
        unique=True)
    clients = models.ManyToManyField(Client)
    activity_date = models.DateField(
        blank=True,
        null=True)
    activity_cost = models.DecimalField(
        max_digits = 10,
        decimal_places = 2,
        blank=True,
        null=True)
    type_of_activity = models.CharField(
        max_length = 50,
        blank=True)
    notes = models.CharField(
        max_length = 500,
        blank=True)
    slug = models.SlugField(
        max_length = 31,
        unique = True)

    class Meta:
        ordering = ['activity_date']

    def __str__(self):
        return self.type_of_activity + "-" + str(self.activity_ID)

    def get_absolute_url(self):
        return reverse('activity_detail',
                       kwargs={'slug': self.slug})

    def get_update_url(self):
        return reverse('activity_update',
                       kwargs={'slug': self.slug})

    def get_delete_url(self):
        return reverse('activity_delete',
                       kwargs={'slug': self.slug})

class Payment(models.Model):
    ''' Model that represents payments made from client
    to WKDAIS.  Has Fields payment_form, check_number, payment_date,
    payment_amount, and client.  Also has functions get_absolute_url,
    and get_update_url.'''

    PAYMENT_FORMS = (
        ('C', 'Cash'),
        ('K', 'Check'),
        ('V', 'Credit Card'),
    )
    payment_form = models.CharField(max_length=1,
                                    choices=PAYMENT_FORMS)
    check_number = models.IntegerField(
        blank=True,
        null=True,
        )
    payment_date = models.DateField()
    payment_amount = models.DecimalField(
        max_digits=10,
        decimal_places=2)
    client = models.ForeignKey(Client)

    def __str__(self):
        return (str(self.payment_amount) + " "
                + self.client.__str__() + " "
                + str(self.payment_date))

    # this should maybe be in the client model,
    # as it lists the payments for one client.
    # Maybe move later.
    def get_absolute_url(self):
        return reverse('payment_detail',
                       kwargs={'id': self.id})

    def get_delete_url(self):
        return reverse('payment_delete',
                       kwargs={'id': self.id})

wkdais_project/client_info/forms.py
from django import forms
from django.forms import ModelForm, SlugField
from django.core.exceptions import ValidationError
from django.utils.text import slugify

from .models import Client, ClientActivities, Payment


class ClientForm(forms.ModelForm):

    slug = forms.SlugField(disabled=True, required=False)

    class Meta:
        model = Client
        fields = '__all__'

    def clean_first_name(self):
        capitalized_name = self.cleaned_data['first_name'].title()
        return capitalized_name

    def clean_last_name(self):
        capitalized_name = self.cleaned_data['last_name'].title()
        return capitalized_name

    def clean_middle_name(self):
        capitalized_name = self.cleaned_data['middle_name'].title()
        return capitalized_name

    def clean_slug(self):
        '''Creates a new slug using a combo of first and last name,
        if client with that first and last name already exists, makes
        a slug that is first_middle_last name.'''

        client_set = Client.objects.all()
        new_slug = (
            self.cleaned_data['first_name'].lower()
            + "_" +
            self.cleaned_data['last_name'].lower()
        )
        for person in client_set:
            if person.slug == new_slug:
                #new_slug += "_" + self.cleaned_data['middle_name'].lower()
                new_slug = (
                    self.cleaned_data['first_name'].lower() + "_" +
                    self.cleaned_data['middle_name'].lower() + "_" +
                    self.cleaned_data['last_name'].lower()
                )
        return slugify(new_slug)

class ActivityForm(forms.ModelForm):

    class Meta:
        model = ClientActivities
        fields = '__all__'

    def clean_slug(self):
        '''Creates a new slug that is a combo of activity type and activity
        number.'''

        new_slug = (self.cleaned_data['type_of_activity'].lower()
                    + "_" +
                    str(self.cleaned_data['activity_ID'])
                   )

        return slugify(new_slug)

class PaymentForm(forms.ModelForm):

    class Meta:
        model = Payment
        fields = '__all__'

wkdais_project/client_info/templates/client_info/activity_confirm_delete.html
{% extends parent_template|default:"client_info/base_client_info.html" %}

{% block content %}
<div>
  <div class="container-fluid">
    <form
      action="{{ clientactivities.get_delete_url }}"
      method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <p>
      Are you sure you want to delete Activity:
      <b>{{ clientactivities.type_of_activity|title }}</b> on <b>
          {{ clientactivities.activity_date }}</b></p>
    <em>This cannot be undone!</em>
    <br>
    <a href="{{ clientactivities.get_absolute_url }}">
      <button class="btn btn-large btn-primary"
              type="button">
        Cancel</button></a>
    <button class="btn btn-large btn-danger"
            type="submit">
      Delete Activity</button>
    </form>
  </div>
</div>
{% endblock %}

wkdais_project/client_info/templates/client_info/activity_create.html
{% extends parent_template|default:"client_info/base_client_info.html" %}

{% block content %}
<div>
  <div class="container-fluid">
    <form
      action="{% url 'activity_create' %}"
      method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">
      Create Activity</button>
    </form>
  </div>
</div>
{% endblock %}

wkdais_project/client_info/templates/client_info/activity_detail.html
{% extends parent_template|default:"client_info/base_client_info.html" %}

{% block content %}
<div class="container-fluid">
  <h2>{{ activity.activity_ID }} - {{ activity.type_of_activity|title }}</h2>
  <div>
    <ul>
      <li>Activity ID: {{ activity.activity_ID }}</li>
      <li>Activity Type: {{ activity.type_of_activity }}</li>
      <li>Activity Date: {{ activity.activity_date }}</li>
      <li>Activity Cost: {{ activity.activity_cost }}</li>
      <li>Activity Notes: {{ activity.notes }}</li>
      <li>Activity Slug: {{ activity.slug }}</li>
      <li>Clients at Activity: 
        <ul>
          {% for client in activity.clients.all %}
        <li><a href="{{ client.get_absolute_url }}">{{ client.first_name }}
            {{client.last_name }}</a></li>
          {% endfor %}
        </ul>
      </li>
    </ul>
  </div>
<a href="{{ activity.get_delete_url }}">
  <button class="btn btn-large btn-danger">Delete Activity</button>
</a>
<a href="{{ activity.get_update_url }}">
  <button class="btn btn-large btn-primary">Update Activity</button>
</a>
</div>
{% endblock %}

wkdais_project/client_info/templates/client_info/activity_list.html
{% extends parent_template|default:"client_info/base_client_info.html" %}
{% comment %}
  Date: 07/22/17
  Name: client_list.html
  Description: HTML template page that lists all clients in database
{% endcomment %}

{% block content %}
<div class="container-fluid">
  <h1>Activities</h1>

  <ul>
  {% for activity in activity_list %}
    <li>
      <a href='{{ activity.get_absolute_url }}'>{{ activity.activity_ID }} - 
        {{ activity.type_of_activity|title }}</a>
    </li>
  {% endfor %}
  </ul>
  <a href="{% url 'activity_create' %}">
     <button class="btn btn-primary">Create New Activity</button>
  </a>
</div>
{% endblock %}

wkdais_project/client_info/templates/client_info/activity_update_form.html
{% extends parent_template|default:"client_info/base_client_info.html" %}

{% comment %}
Name: Chris Humphreys
Date: 08/03/17
Description: HTML template for activity update pages
{% endcomment %}

{% block content %}
<div class="container-fluid">
<h2>{{ client.first_name|title }} {{ client.last_name|title }}</h2>
  <div>
    <form action="{{ activity.get_update_url }}"
          method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">
        Update Activity</button>
    </form>
  </div>
</div>
{% endblock %}

wkdais_project/client_info/templates/client_info/base_client_info.html
{% extends parent_template|default:"base.html" %}

wkdais_project/client_info/templates/client_info/client.html
{% extends parent_template|default:"client_info/base_client_info.html" %}

{% block content %}
<div class="container-fluid">
<h2>{{ client.first_name|title }} {{ client.last_name|title }}</h2>

<ul>
  <li>First Name: {{ client.first_name }}</li>
  <li>Middle Name: {{ client.middle_name }}</li>
  <li>Last Name: {{ client.last_name }}</li>
  <li>Birth Date: {{ client.birth_date }}</li>
  <li>Conviction Date: {{ client.conviction_date }}</li>
  <li>Case Number: {{ client.case_number }}</li>
  <li>Assessed Date: {{ client.assessed_date }}</li>
  <li>Intake Date: {{ client.intake_date }}</li>
  <li>Balance: {{ client.balance_cf }}</li>
  <li>Program Completed: {{ client.complete }}</li>
  <li>Amount Billed: {{ client.total_billed }}</li>
  <li>Amount Paid: {{ client.total_paid }}</li>
  <li>Paid in Full: {{ client.paid_in_full }}</li>
  <li>Date Paid in Full: {{ client.paid_in_full_date }}</li>
  <li>Compliant: {{ client.non_compliant }}</li>
  <li>Non-Compliant Date: {{ client.no_compliant_date }}</li>
  <li>Active: {{ client.inactive }}</li>
  <li>Inactive Date: {{ client.inactive_date }}</li>
  <li>Street Address: {{ client.street_address }}</li>
  <li>City: {{ client.city }}</li>
  <li>State: {{ client.state }}</li>
  <li>Zip Code: {{ client.zip_code }}</li>
  <li>Phone Number: {{ client.phone_number }}</li>
  <li>Work Phone Number: {{ client.work_phone_number }}</li>
  <li>Social Security Number: {{ client.ssn }}</li>
  <li>Court: {{ client.court }}</li>
  <li>Office Number: {{ client.office_number }}</li>
  <li>DUI: {{ client.dui }}</li>
  <li>Comments: {{ client.comments }}</li>
  <li>Program: {{ client.program }}</li>
  <li>BYN: {{ client.byn }}</li>
</ul>

<h2>Activities Attended</h2>
  <ul>
    {% for activity in activities %}
    <li>
      <a href = "{{ activity.get_absolute_url }}">
      {{ activity.activity_ID }}-{{ activity.type_of_activity}}</a>
    </li>
    {% endfor %}
  </ul>
<a href="{{ client.get_delete_url }}">
  <button class="btn btn-large btn-danger">Delete Client</button>
</a>
<a href="{{ client.get_update_url }}">
  <button class="btn btn-large btn-primary">Update Client Info</button>
</a>
<a href="{{ client.get_payments_url }}">
  <button class="btn btn-large btn-info">View Payments</button>
</a>
</div>
{% endblock %}

wkdais_project/client_info/templates/client_info/client_confirm_delete.html
{% extends parent_template|default:"client_info/base_client_info.html" %}

{% block content %}
<div>
  <div class="container-fluid">
    <form
      action="{{ client.get_delete_url }}"
      method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <p>
      Are you sure you want to delete Client:
      <b>{{ client.first_name|title }} {{ client.last_name|title }}</b></p>
    <em>This cannot be undone!</em>
    <br>
    <a href="{{ client.get_absolute_url }}">
      <button class="btn btn-large btn-primary"
              type="button">
        Cancel</button></a>
    <button class="btn btn-large btn-danger"
            type="submit">
      Delete Client</button>
    </form>
  </div>
</div>
{% endblock %}

wkdais_project/client_info/templates/client_info/client_list.html
{% extends parent_template|default:"client_info/base_client_info.html" %}
{% comment %}
  Date: 07/22/17
  Name: client_list.html
  Description: HTML template page that lists all clients in database
{% endcomment %}

{% block content %}
<div class="container-fluid">
  <h1>Clients</h1>

  <ul>
  {% for client in client_list %}
    <li>
      <a href='{{ client.get_absolute_url }}'>{{ client.first_name|title }}
        {{ client.last_name|title }}</a>
    </li>
  {% endfor %}
  </ul>
  <a href="{% url 'client_create' %}">
     <button class="btn btn-primary">Create New Client</button>
  </a>
 <a href="{% url 'payment_create' %}">
     <button class="btn btn-primary">Add Payment</button>
  </a></div>
{% endblock %}

wkdais_project/client_info/templates/client_info/client_payments_list.html
{% extends parent_template|default:"client_info/base_client_info.html" %}
{% comment %}
  Date: 07/22/17
  Name: client_payments_list.html
  Description: HTML template page that lists all payments made by a client
{% endcomment %}

{% block content %}
<div class="container-fluid">
  <h1>Payments</h1>

  <ul>
  {% for payment in payments %}
    <li> <a href = "{{ payment.get_absolute_url }}">
      {{ payment.payment_date }} - {{ payment.payment_amount }}
      </a>
    </li>
  {% endfor %}
  </ul>
  <a href = "{{ client.get_receipt_url }}">
    <button class='btn btn-info'>Print Receipt</button></a>
</div>
{% endblock %}

wkdais_project/client_info/templates/client_info/client_update_form.html
{% extends parent_template|default:"client_info/base_client_info.html" %}

{% comment %}
Name: Chris Humphreys
Date: 07/22/17
Description: HTML template for client update pages
{% endcomment %}

{% block content %}
<div class="container-fluid">
<h2>{{ client.first_name|title }} {{ client.last_name|title }}</h2>
  <div>
    <form action="{{ client.get_update_url }}"
          method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-primary">
        Update Client</button>
    </form>
  </div>
</div>
{% endblock %}

wkdais_project/client_info/templates/client_info/payment_confirm_delete.html
{% extends parent_template|default:"client_info/base_client_info.html" %}

{% comment %}
Name: Chris Humphreys
Date: 08/12/17
Description: HTML template for payment delete. 
{% endcomment %}

{% block content %}
<div>
  <div class="container-fluid">
    <form
      action="{{ payment.get_delete_url }}"
      method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <p>
      Are you sure you want to delete Payment:
      <b>{{ payment|title }}</b></br> 
    <em>This cannot be undone!</em>
    <br>
    <a href="{{ clientactivities.get_absolute_url }}">
      <button class="btn btn-large btn-primary"
              type="button">
        Cancel</button></a>
    <button class="btn btn-large btn-danger"
            type="submit">
      Delete Payment</button>
    </form>
  </div>
</div>
{% endblock %}

wkdais_project/client_info/templates/client_info/payment_create.html
{% extends parent_template|default:"client_info/base_client_info.html" %}
{% comment %}
name of check_number field is check_number
  use 'input[name=check_number]' to access with jquery
name of payment_form field is payment_form
  use 'selection[name=payment_form]' to access with jquery

{% endcomment %}

{% block jquery %}
// This function hides the check number field
//  if the user selects an option other than check 
$("#id_payment_form").change(function () {
  var selected_option = $('#id_payment_form').val();
  if (selected_option === 'K') {
      $('#id_check_number').show();
      $("label[for='id_check_number']").show();
  }
  if (selected_option != 'K') {
      $("label[for='id_check_number']").hide();
      $('#id_check_number').hide();
  }
})
{% endblock %}

{% block content %}
<div>
  <div class="container-fluid">
    <form
      action="{% url 'payment_create' %}"
      method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">
      Create Payment</button>
    </form>
  </div>
</div>
{% endblock %}

wkdais_project/client_info/templates/client_info/payment_detail.html
{% extends parent_template|default:"client_info/base_client_info.html" %}

{% comment %}
Name: Chris Humphreys
Date: 08/05/17
Description: HTML template for payment detail pages
{% endcomment %}

{% block content %}
<div class="container-fluid">
  <h2>{{ payment.client|title }} - {{ payment.payment_date }}</h2>
  <div>
    <ul>
      <li>Payment Form:
        {% if payment.payment_form == 'K' %}
          Check</li>
        <li>Check Number: {{ payment.check_number }}</li>
        {% elif payment.payment_form == 'C' %}
          Cash</li>
        {% elif payment.payment_form == 'V' %}
          Credit Card</li>
      {% endif %}
      <li>Payment Date: {{ payment.payment_date }}</li>
      <li>Payment Amount: {{ payment.payment_amount }}</li>
    </ul>
  <a href = "{{ payment.get_delete_url }}">
    <button class='btn btn-danger'>Delete</button></a>
  </div>
</div>
{% endblock %}